name: check-demo
          
  open:
    name: Open Issue
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v3
        with:
           script: console.log(context)
      - uses: actions/github-script@v3
        with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
             github.issues.createComment({
               issue_number: 5,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: "Updated Successfully"
             })
      - uses: actions/checkout@v1
      
